project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from members.views import indexr, health, search

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', indexr),
    url(r'^health$', health),
    url(r'^search$', search, name='members-search'),
    url(r'^admin/', include(admin.site.urls)),
]

members/models.py
from django.db import models


class Legislature(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField(null=True)

    def __str__(self): return self.name


class Party(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ImageField(null=True, blank=True)

    def __str__(self): return self.name


class Member(models.Model):
    name = models.CharField(max_length=200)
    party = models.ForeignKey(Party)
    picture = models.ImageField()

    def __str__(self): return self.name


class Role(models.Model):
    name = models.CharField(max_length=200)
    government = models.BooleanField()
    legislature = models.ForeignKey(Legislature)
    member = models.ForeignKey(Member)

    def __str__(self): return self.name


class Company(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    logo = models.ImageField(null=True, blank=True)

    def __str__(self): return self.name


class Connection(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    member = models.ForeignKey(Member)
    reference = models.URLField(blank=True, null=True)
    company = models.ForeignKey(Company, null=True, blank=True)

    def __str__(self): return self.name

members/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Member, Connection

# def index(request):
#     hostname = os.getenv('HOSTNAME', 'unknown')
#     PageView.objects.create(hostname=hostname)

#     return render(request, 'welcome/index.html', {
#         'hostname': hostname,
#         'database': database.info(),
#         'count': PageView.objects.count()
#     })


def health(request):
    return HttpResponse("200")


def indexr(request):
    return render(request, 'index.html')


def search(request):
    term = request.GET.get('term', '')
    connections = Connection.objects.filter(description__search=term)
    return render(request, 'index.html', {'connections': connections, 'term': term})

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>The Connector</title>

    <!-- Bootstrap -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
  </head>
  <body>
    <img id="header" class="img-responsive" src="{% static 'img/header.png' %}" alt="" />
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <img src="{% static 'img/logo.svg' %}" alt="" />
        </div>
      </div>
      <div class="row search top-buffer">
        <div class="row">
          <div class="col-md-6 col-md-offset-1">
            <span class="search-for">Search for...</span>
          </div>
        </div>
        <div class="row">
          <form action="{% url 'members-search' %}">
            <div class="col-md-8 col-md-offset-1">
              <div class="form-group">
                <input type="text" class="form-control" id="query-term" name="term" {% if term %} value="{{ term }}" {% endif%} placeholder="Search connection">
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <button type="submit" class="btn btn-default btn-block"><b>SEARCH</b></button>
              </div>
            </div>
          </form>
        </div>
        {% for connection in connections %}
        <div class="row">
          <div class="col-md-2 col-md-offset-1 connection-member">
            <img class="img-responsive" src="{{connection.member.picture.url}}" alt="" />
            <h6>{{connection.member.name}}</h6>
            {% if connection.member.role_set.all %}
            <h6>{{connection.member.role_set.all.0.name}}  {{connection.member.role_set.all.0.legislature}}</h6>
            {% endif %}
          </div>
          <div class="col-md-2 company">
            <img class="img-responsive" src="{{connection.company.logo.url}}" alt="" />
          </div>
          <div class="col-md-7 connection">
            <a target="blank" href="{{connection.reference}}">
              <p> {{connection.description}}</p>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
      {% if not term %}
      <div class="row">
        <img class="img-responsive" src="{% static 'img/placeholder.jpg' %}" alt="" />
      </div>
      {% endif %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>